### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by otchau57** [andrewwang84/94Orig#5]
got this errors in heroku works fine in web but bot doesn't responds

`2020-07-14T06:55:28.216556+00:00 app[web.1]: TypeError: Cannot read property 'statusCode' of undefined
2020-07-14T06:55:28.216556+00:00 app[web.1]:     at Request._callback (/app/telegram.js:121:30)
2020-07-14T06:55:28.216561+00:00 app[web.1]:     at self.callback (/app/node_modules/request/request.js:185:22)
2020-07-14T06:55:28.216561+00:00 app[web.1]:     at Request.emit (events.js:182:13)
2020-07-14T06:55:28.216562+00:00 app[web.1]:     at Request.onRequestError (/app/node_modules/request/request.js:881:8)
2020-07-14T06:55:28.216562+00:00 app[web.1]:     at ClientRequest.emit (events.js:182:13)
2020-07-14T06:55:28.216563+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:391:9)
2020-07-14T06:55:28.216563+00:00 app[web.1]:     at TLSSocket.emit (events.js:182:13)
2020-07-14T06:55:28.216563+00:00 app[web.1]:     at emitErrorNT (internal/streams/destroy.js:82:8)
2020-07-14T06:55:28.216564+00:00 app[web.1]:     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
2020-07-14T06:55:28.216564+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-07-14T06:55:28.224388+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-07-14T06:55:28.224826+00:00 app[web.1]: npm ERR! errno 1
2020-07-14T06:55:28.225868+00:00 app[web.1]: npm ERR! 94orig@0.0.0 start: `node ./bin/www`
2020-07-14T06:55:28.226031+00:00 app[web.1]: npm ERR! Exit status 1
2020-07-14T06:55:28.226319+00:00 app[web.1]: npm ERR! 
2020-07-14T06:55:28.226488+00:00 app[web.1]: npm ERR! Failed at the 94orig@0.0.0 start script.
2020-07-14T06:55:28.226678+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-07-14T06:55:28.230612+00:00 app[web.1]: 
2020-07-14T06:55:28.230820+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-07-14T06:55:28.230954+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-07-14T06_55_28_227Z-debug.log
2020-07-14T06:55:28.285607+00:00 heroku[web.1]: Process exited with status 1
2020-07-14T06:55:28.334408+00:00 heroku[web.1]: State changed from up to crashed`

**Comment by andrewwang84** [comment]
What do you mean "works fine in web" ? How did you deploy it to heroku?

**Comment by otchau57** [comment]
by your deploy button? oh right it worked for few minutes then i started the bot and it crashed this happened

**Comment by andrewwang84** [comment]
app.json updated so please try it again
